/**
 * Character Card Generation
 *
 * Converts parsed character data into Character Card V2 format
 * compatible with SillyTavern and other AI frontends.
 */

import { corsHeaders } from './utils/cors';

export interface CharacterCardV2 {
  spec: 'chara_card_v2';
  spec_version: '2.0';
  data: {
    name: string;
    description: string;
    personality: string;
    scenario: string;
    first_mes: string;
    mes_example: string;
    creator_notes: string;
    system_prompt: string;
    post_history_instructions: string;
    alternate_greetings: string[];
    character_book?: any;
    tags: string[];
    creator: string;
    character_version: string;
    extensions: Record<string, any>;
  };
}

export interface CharacterCardRequest {
  characterName: string;
  content: string;
  scenario?: string;
  firstMessage?: string;
  personality?: string;
  tags?: string[];
  creator?: string;
}

/**
 * Create Character Card V2 data structure
 */
export function createCharacterCard(data: CharacterCardRequest): CharacterCardV2 {
  return {
    spec: 'chara_card_v2',
    spec_version: '2.0',
    data: {
      name: data.characterName || 'Character',
      description: data.content || '',
      personality: data.personality || '',
      scenario: data.scenario || '',
      first_mes: data.firstMessage || '',
      mes_example: '',
      creator_notes: 'Generated by Scrapitor',
      system_prompt: '',
      post_history_instructions: '',
      alternate_greetings: [],
      character_book: null,
      tags: data.tags || [],
      creator: data.creator || 'Scrapitor',
      character_version: '1.0',
      extensions: {
        scrapitor: {
          generated_at: new Date().toISOString(),
          version: '2.0-workers',
        },
      },
    },
  };
}

/**
 * Handle character card creation endpoint
 */
export async function handleCharacterCard(request: Request): Promise<Response> {
  try {
    const body = await request.json();

    if (!body.characterName || !body.content) {
      return new Response(
        JSON.stringify({
          error: 'Invalid request: characterName and content are required',
        }),
        {
          status: 400,
          headers: {
            'Content-Type': 'application/json',
            ...corsHeaders(request),
          },
        }
      );
    }

    const cardData = createCharacterCard({
      characterName: body.characterName,
      content: body.content,
      scenario: body.scenario,
      firstMessage: body.firstMessage,
      personality: body.personality,
      tags: body.tags,
      creator: body.creator,
    });

    // Return the card data as JSON
    // Client will handle PNG embedding
    return new Response(JSON.stringify(cardData), {
      headers: {
        'Content-Type': 'application/json',
        ...corsHeaders(request),
      },
    });
  } catch (error) {
    console.error('Character card error:', error);
    return new Response(
      JSON.stringify({
        error: 'Character card generation failed',
        message: error instanceof Error ? error.message : 'Unknown error',
      }),
      {
        status: 500,
        headers: {
          'Content-Type': 'application/json',
          ...corsHeaders(request),
        },
      }
    );
  }
}
